aiidalab/aiidalab

Pipfile, README.md, requirements.txt
=> Remove python2 dependencies

requirements.txt
While `aiida-core==1.0.1` depends on `django==1.11.25`, the newest `develop` version of `aiida-core` already shows that it can support `django~=2.2` with no issue. So setting the dependency of `aiidalab` to `django==1.11.28` is not a big issue, but will indeed solve a vulnerability.
When we update to `aiida-core==1.1.0`, however, this will be updated in any case. So it is in some ways also a temporary dependency bump - again, to remove the vulnerability of earlier `django` version.
=> Update django dep to 1.11.28

aiidalab/home.py
When only two apps were installed the function `move_updown` wasn't moving apps down.
=> fix move_updown function.

.github/workflows/ci.yml
I think the test structure highlights that maybe, decoupling the `aiidalab` package from the home app was the wrong move after all. Regardless, I suggest that we move forward in this way for now and reconsider this structure at a later stage.
=> Add GitHub actions continuous-integration workflow for testing.

aiidalab/app.py, setup.json
This change set refactors the app registry data management to be stored within a dataclass. This makes it easier to validate that data and keep it self-consistent. Furthermore, it makes it easier to understand where that data is coming from and check whether it is available in downstream functions.
=> Implement AppRegistryData data class to hold app registry data.

aiidalab/app.py
@CasperWA I previously accepted your suggestion to add `<..>` delimiters to the `__repr__` return value of the `AiidaLabApp` class (as part of #81) however, the convention is not use these delimiters when `__repr__` actually returns a valid Python expressions, see also here:
* https://docs.python.org/3.7/library/functions.html#repr
* https://stackoverflow.com/a/1984177
This PR reverts that change.
=> Make return value of AiidaLabApp.__repr__() valid Python expression.

aiidalab/app.py, aiidalab/environment.py, aiidalab/kernel.py, aiidalab/utils.py, aiidalab/widgets.py
fixes #41 
fixes #68 
fixes #69 
This change set extends the app installation process to install a dedicated app-specific kernel where all app-specific dependencies are installed. The kernel installation process involves the setup of a virtual environment and the subsequent installation of the Python executable as kernel into the Jupyter kernelspec configuration within user space. The virtual environment uses system packages, so dependencies that are already present in the system environment, are used directly and not installed again.
The kernel is uniquely identified by its name which is a function of the app name, which prevents accidental name collisions. To ensure that app-specific notebooks are opened with the correct kernel, one must use the `aiidalab.utils.url_for()` function when …
=> Install app dependencies with dedicated environment

aiidalab/app.py, tests/test_app.py
Makes installation flow robust against detached HEAD states.
=> Determine remote branch from release line instead of checked out branch.

aiidalab/app.py, tests/test_app.py
This is more in line with the URL specification (RFC 3986, 3.5) that
defines that the fragment section of a URL is not transmitted to the
server endpoint and evaluated on the client side to denote "some portion
or subset of the primary resource".
Using '#' instead of '@' also avoids potential confusion with the use of
the symbol in the context of `pip install`, which has highly related,
but not identical meaning.
=> Use the number sign '#' instead of '@' to indicate release line.

README.md, aiidalab/__init__.py, aiidalab/app.py, aiidalab/config.py, aiidalab/git_util.py, aiidalab/utils.py, setup.json, setup.py
Readme was referring to `aiidalab` as a meta-package. It is not
true anymore, as now the package contains the core features of the
AiiDAlab platform. Additionally, the link to the Travis tests has been
corrected.
=> Rename AiiDA lab to AiiDAlab and modify README.

aiidalab/__init__.py, aiidalab/config.py
This change sets makes it possible to configure aiidalab with a config file (`~/aiidalab.toml`). The primary use case is to be able to override some of the configuration values temporarily during development. However, the environment variables still take precedence by default unless the `develop = True` key is set. In that case aiidalab will actively warn the user with a little banner to ensure that we don't forget that the environment is modified:
=> Add specification of config in local config file.

setup.json
This is needed to work on Quantum Mobile where the standard Python
version is 3.6. The >5.0 version of traitlets does not support it.
=> Downgrade traitlets dependency to `~=4.0`

aiidalab/config.py
Replace the link to the apps_meta.json file
from: https://aiidalab.materialscloud.org/appsdata/apps_meta.json
to: https://aiidalab.github.io/aiidalab-registry/apps_meta.json
=> Modify the link to the apps_meta.json file.

aiidalab/utils.py
Because of this, if https://aiidalab.materialscloud.org/ is offline (as it is currently),
you can't even start aiidalab 😒.
I suggest  you also look through the rest of the code-base,
to check if there is anywhere else that assumes an internet connection.
=> 🐛 FIX: Unloadable home page when offline

aiidalab/app.py
This is to work-around issues on some network file systems, that may
have lingering locks on files within the repository directory. The clean
up of the trash directory should be handled as a service.
=> Do not delete apps directly, but move them into a trash directory.

docs/source/app_development/index.rst, docs/source/app_development/widgets.rst, docs/source/index.rst
* reorder docs according to priority of information (start with aiidalab base widgets, then provide links to more examples, then add some background info for those who are interested)
* revise language
* remove js/python code illustrations for custom widgets - this bloats
this page, would need to be maintained, and should be left to
the ipywidgets docs
=> update widgets docs

aiidalab/app.py, aiidalab/utils.py
1. Any (unstaged or staged) changes will set the app version to "unknown".
2. Remove the concept of incompatible versions, as we are now installing
the dependenices.
3. Show compatibility info only for the currently installed version.
4. Show all available prereleases or releases even if they are
incompatible with the current environment.
5. Reduce the caching time of the find_installed_packages function. This
is needed to update the compatibility info of a freshly installed package.
=> Update package management logic.

aiidalab/__main__.py, aiidalab/app.py, aiidalab/environment.py, aiidalab/fetch.py, aiidalab/git_util.py, aiidalab/metadata.py, aiidalab/utils.py, setup.cfg
- Enables the local installation of non-registered apps.
- Local metadata used as fallback in cases where the registry cannot be
reached.
- Adds the 'parse-app-repo' aiidalab command that shows what metadata
and environment specification is parsed from a repository.
=> Parse metadata from app repository for non-registered apps.

aiidalab/__main__.py, aiidalab/app.py, aiidalab/utils.py
- The state where the registry cannot be reached and where an app is
not registered are clearly distinguished. It should be noted that when
the registry cannot be reached, it is not possible to determine whether
an app is hypothetically registered or not.
- Replace `updates_available` trait with `remote_update_status`.
To support more than three states.
- Refactor version determination.
Fixes #221.
=> Distinguish between non-registered and registry cannot be reached.

aiidalab/app.py
Unless a prerelease is already installed or explicit user opt-in.
Note: this fixes a regression that was introduced with #222.
=> Fix: Correctly handle updates for apps with prereleases

aiidalab/__main__.py
When trying to install the app from a [PEP 508](https://www.python.org/dev/peps/pep-0508/) form with the branch specified, the `@` is wrongly checked and without a print useful message.
=> Improve error message in install with url

aiidalab/utils.py
The function would previously fail whenever the were any Python
packages installed in editable mode within the environment.
=> Fix "find_installed_packages()" util function for editable installs.

setup.cfg
To workaround incompatibility (https://github.com/pallets/jinja/issues/1587).
=> Dependencies: Pin MarkupSafe.

aiidalab/app.py
This option was deprecated with version 21.3.
Fixes #296.
=> Do not use pip's in-tree-build option.

aiidalab/app.py, aiidalab/utils.py
Check the exit code of forked subprocess to ensure that issues actually propagate up
and that the installation process does not simply proceed despite errors, e.g., during
the installation of dependencies.
=> Check forked process calls for success during app installation.

aiidalab/app.py
I just lost an hour when trying to understand why the home app was throwing an error about a missing logo key, until I realized that I had an extra folder in the `apps/` folder. With this change I would have seen the issue immediately at least.
=> Better error if logo/categories metadata are missing

aiidalab/app.py
Before this change, if a  `post_install` script failed when installing an app we would get
```
raise CalledProcessError
TypeError: __init__() missing 2 required positional arguments: 'returncode' and 'cmd'
```
More info at:
https://docs.python.org/3/library/subprocess.html#subprocess.CalledProcessError
=> Fix: Add missing arguments to raised exception

aiidalab/metadata.py
The `categories` provided in the metadata will be parsed as a string, but a list is required. 
It is now allowed to provide a single category that is parsed as a list. 
Or the list separated by newlines will be parsed as a list.
Closes #257
=> Support parsing categories from setup.cfg

aiidalab/app.py
Method threading.Thread.isAlive has been removed in Python 3.9, https://bugs.python.org/issue37804
Closes #340
I don't have a capacity to actually test this, leaving up to the reviewers, sorry.
=> FIX: Change isAlive to is_alive

setup.cfg
Watchdog dependency seems to be used for live monitoring of AiiDAlab app installation process (I didn't look too closely what it actually does though). The old version prevents upgrade to Python 3.10.
I checked the watchdog Changelog and it seems this should be a seamless update. I have manually tested installation from the Appstore on this branch and it seems to work. Would be good if somebody else with more experience with Appstore tested as well. You can use this image: `ghcr.io/aiidalab/full-stack:pr-337` Note that this image is build with Python 3.10, so you might as well test other things. :-)
=> Deps: Bump watchdog

aiidalab/app.py
This is the more direct cause of https://github.com/aiidalab/aiidalab-home/issues/100, rather than https://github.com/aiidalab/aiidalab/pull/349.
In the package, there is already a context manager `_show_busy` provide to hold the display before the operations are running. However, this context manager only set the `self.busy` to a bool, which will be overridden unexpectedly if the `_show_busy` is embedded in itself. This happened for `install_app`, `updata_app` and `uninstall_app`, they are supposed to use `_show_busy` to prevent information to be displayed, but inside these function also call `refresh` which have another `_show_busy`. I add a counter to properly set the `busy` traitlets. It is `False` (which means not busy) when it counts down to zero.
=> add count to proper set busy traitlets

aiidalab/app.py, setup.cfg
fixes #358 
The watchdog file system monitor introduce a new event handler `INOPNED` for when file opened. The new "file opened" event is included by default in all events: https://github.com/gorakhargosh/watchdog/blob/v2.3.0/src/watchdog/events.py#L289
The details are discussed at https://github.com/gorakhargosh/watchdog/issues/949, we encounter the same issue. But we use `on_any_event` explicitly, we adopt the same change as https://github.com/gorakhargosh/watchdog/commit/25a2d1fec55fc32f97055ba827c8ce7b959acb34 to avoid spammed by the opened event update.
=> watchdog file system check not trigger refresh on file opened

.github/workflows/ci.yml, aiidalab/app.py, aiidalab/utils.py, setup.cfg, tests/conftest.py, tests/test_appclass.py, tests/test_appdataclass.py
This PR essentially reverts some of the changes made in #301, which dropped support for the old Docker stack.
We reintroduce support by:
1. Detecting `aiida-core` version and running `reentry scan` only for AiiDA 1.x
2. Dropping dependency on `aiida-core` in setup.cfg. I don't really see a reason why this package should depend on aiida-core. This also makes local development easier since one does not need to have aiida-core in the dev environment. Also makes installation in our CI faster.
Closes #348
=> Make the package compatible with old docker stack again

aiidalab/__main__.py, aiidalab/config.py, tests/test_appclass.py
Based on user feedback at the last AiiDA hackathon,
`verdi` command now supports `-h` option as an alias for `--help`, as of https://github.com/aiidateam/aiida-core/pull/5792
Let's do the same thing here.
If you agree with this, I'll submit the same PR for `aiidalab-launch` as well.
=> CLI: Add -h option as an alias for --help

aiidalab/app.py, tests/test_appclass.py
fixes #361 
I did the minimal change by replace `_stop_flag` with the `threading.Event` object.
=> Using event to log the stop status of the monitor threading

aiidalab/__main__.py, aiidalab/app.py, tests/conftest.py, tests/test_appclass.py, tests/test_appdataclass.py
fixes #360 
The `available_versions` of _AiidalabApp data class object not considered core compatible. The core compatible check is implement independently and sporadically when the `available_versions` list is required.  
This commit add the core compatible check inside the function `available_versions` of _AiidalabApp class to get the only usable versions for both when prereleases option is on and off. Therefore the version list conforms with what is shown in the version_to_install dropdown option.
=> available versions list unified by consider prereleases and core compatible in same function

aiidalab/app.py
Previously, we were only catching RuntimeError which left a lot of room for other failures during installation, which would result in an incomplete installation of an app. Generally, there's no way of knowing after-the-fact that the installation ended prematurely, e.g. `aiidalab list` would show the app as installed.
Note that this includes for example `post_install` script failures.
Now we catch everything, including Keyboard interrupts, so that we always trigger the already existing rollback mechanism.
See issue #334 for details of how to reproduce this.
1. Trigger installation of an app from CLI `aiidalab -v install aurora==0.2.1`
2. Interrupt the installation in the middle with Ctrl+C
3. The installation should rollback. Verify with `aiidalab list` that the app is not installed.
4. …
=> Catch all exceptions when installing app

aiidalab/__main__.py, aiidalab/app.py, tests/test_appclass.py, tests/test_appdataclass.py
fixes #373 
When the app is installed but the app repo gets new commit, the app version will become UNKNOWN. Therefore, the requirements list cannot check with the version from the registered list. Rather the requirements list needs to access from the local repo. 
Check requirements upon local repo happened for the app not registered but also should be for the app detached. The condition is added for detached app for incompatibility check.
=> incompatibility check for app detached will go through the local repo

aiidalab/registry/templates/base.html, docs/source/conf.py, docs/source/usage/index.rst
Solves #371 
Updated the URLs used in the footer of the application to use the correct links. Previously, the links were pointing to the wrong resources, but have been updated to point to the correct URLs. This includes updating the links to the AiiDAlab registry page in the aiidalab-registry repository. These changes ensure that users can access the correct resources from the footer of the application.
This pull request fixes an issue in the parent file `base.html` at https://github.com/aiidalab/aiidalab/blob/50498b08ea77937cb8af0e8d753446dd17b6d637/aiidalab/registry/templates/base.html#L3 which was causing issues in the child file `layout.html` at https://github.com/aiidalab/aiidalab-registry/blob/8bc5d00fffa2016f562d065d81bd5a111c99479e/src/templates/layout.html#L8. The issue was …
=> Fix base.html URLs

aiidalab/app.py
Step toward #342.
In this PR, we still require the `setup.cfg`, but instead of dummy `setup.py`, we can now user a rudimentary `pyproject.toml` to declare the build dependencies explicitly.
=> Allow for removing setup.py in favour of simple pyproject.toml

setup.cfg
The pin was a workaround around an issue with an old Jinja 2.x version, but we have since then updated Jinja so it should not be neccessary anymore.
See https://github.com/aiidalab/aiidalab/pull/264 for details.
NOTE: This pin also prevents potential upgrade to Python 3.11
=> Unpin MarkupSafe package

.gitignore, aiidalab/config.py, aiidalab/git_util.py, aiidalab/metadata.py, setup.cfg
Step towards #363. I am definitely not a typing expert, taking this work as an opportunity to learn. Would appreciate help to get rid of the `type: ignore`s (although some of them seems to be caused by `dulwich` package not providing types).
=> Add typing to git_util.py,  metadata.py and config.py

.pre-commit-config.yaml, aiidalab/app.py, pyproject.toml, setup.cfg, tox.ini
Update of mypy now detects some new issues. Not sure if these are real or a mypy bug, need to investigate more.
EDIT: Looks like mypy was right and we were not ensuring that we return a proper types in one of the functions. The refactor I made is not very pretty but does the trick. Further cleanup would be more work I think.
=> Pre-commit update + fix docs build

aiidalab/utils.py
Fix #423 .
After installing or updating a plugin package, one needs to restart the daemon with the ``--reset`` flag for changes to take effect. 
Besides, in the latest aiida-core branch, this is now the default. https://github.com/aiidateam/aiida-core/pull/6317, thus we need to define the restart command based on aiida-core version
=> Define daemon restart command based on the aiida-core version

.github/dependabot.yml, .pre-commit-config.yaml, aiidalab/__main__.py, aiidalab/app.py, aiidalab/config.py, aiidalab/environment.py, aiidalab/git_util.py, aiidalab/metadata.py, aiidalab/registry/api.py, aiidalab/registry/releases.py, aiidalab/registry/web.py, aiidalab/utils.py, docs/source/conf.py, pyproject.toml, setup.cfg
I've taken ruff config from AWB (with minor modifications as needed).
=> Switch to ruff linter and formatter

.github/workflows/ci.yml, setup.cfg, tests/conftest.py
[uv](https://github.com/astral-sh/uv/issues/2155l) is the new cool kid in the town of Python packaging, from the creators of ruff. It currently serves as a much faster drop-in replacement for pip. 
For the `aiidalab` package, this drops installation time from ~15s to ~2s, which nearly halves the workflow time since the tests we have here are pretty quick.
Couple other small changes (feel free to push back)
- Remove pre-commit section from CI since we use the pre-commit.ci anyway. 
- Don't run tests on both push and pull_request event, this leads to duplication for pull requests coming from origin.
- ~~remove bumpver and pre-commit from direct dev dependencies, as proposed [on Discourse](https://aiida.discourse.group/t/remove-pre-commit-and-bumpver-from-dev-dependencies/325)~~
- get rid of …
=> Use uv to install dependencies in CI

setup.cfg
The `aiidalab` package depends transitively on ipython via `traitlets`, but we do not use it directly in the package so we shouldn't pin its version in the package requirements.
This is currently a blocker for updating the base jupyter image to python 3.10/3.11 in https://github.com/aiidalab/aiidalab-docker-stack/pull/455
=> Remove ipython as a direct dependency

.github/workflows/ci.yml, .gitignore
Currently the line coverage percentage is being artificially inflated by tracking coverage of tests themselves, i.e. the files in the tests/ folder. Let's be honest with ourselves and track what we care about.
Split from #431 so that we actually see coverage increase in that PR.
=> CI: Don't track coverage of tests/

.github/workflows/ci.yml, setup.cfg
Bumped watchdog dependency to support python 3.12
According to changelog there shouldn't be any breaking changes. 🤞
=> Support python 3.12

.github/workflows/ci.yml, aiidalab/app.py, aiidalab/utils.py, setup.cfg
Drop support for the old docker stack, which is no longer maintained (and hopefully not used anywhere!). We can then drop support for Python 3.8 since the new stack started with 3.9
This reverts relevant parts of #355.
=> Drop support for old docker stack and Python-3.8

.github/release.yml, .github/workflows/publish.yml
Adds a configuration for auto-generated release notes to make them a bit nicer:
- Exclude PRs from dependabot and pre-commit-ci bot
- Autogenerate sections based on PR labels.
I've already merged tested this in AWB https://github.com/aiidalab/aiidalab-widgets-base/pull/618 and it seems to work nicely, let's try it here as well.
=> Make auto-generated release notes nicer

aiidalab/utils.py, tests/conftest.py, tests/test_appclass.py, tests/test_cli.py, tests/test_conftest.py
As #196 explains, we now use a global cache for *all* `requests` calls! That's quite scary since it influences apps that import `aiidalab` package, such as AWB or home app! 
Here we fix this using the approach suggested in https://github.com/aiidalab/aiidalab/issues/196#issuecomment-899196469 Moreover, this seems to fix the segfault that we started seeing with `requests_cache>=1.0.0` described in #446.
Fixes #446 ( :crossed_fingers: ). Fixes #196 
Hopefully also fixes #413, I've removed the call to the app registry from tests.
Because we generally want to avoid fetching app index over network in tests, I've tested manually.
1. Launch a container with the latest `ghcr.io/aiidalab/full-stack:edge` image
2. Navigate to the app store page and observe that it crashes with "Kernel died" error, …
=> Fix segfault from requests_cache

docs/source/admin/index.rst
Policy documents are now templated and deployed by each deployment (no longer housed here). This PR adds a note in the documentation regarding the use of these templates.
=> Add documentation section on deploying usage policies

aiidalab/__main__.py
issue #432 
Replaced the deprecated `pkg_resources` module with `importlib.resources` .
This update ensure compatibility with newer Python versions and removes the unnecessary dependency on `setuptools`.
=> Replacing pkg_resource with importlib
