- requirements.txt
- setup.json
> release v19.01.2

- requirements.txt
- setup.json
add requests-cache as a dependency
> Prepare 19.03.1 release

- aiidalab/app.py
- aiidalab/appstore.py
Pylint should pass without warnings/errors.
> Various improvements to code style.

- Pipfile
- requirements.txt
Since aiida-core and many aiida plugins has been stabilized, they were
moved from [dev-packages] to [packages] section of the Pipfle. The 
requirements file has been adapted accordingly.
> Pipfile: move packages from [dev-packages] to [packages] section.

- aiidalab/app.py
- aiidalab/appstore.py
- aiidalab/git_util.py
- aiidalab/home.py
- aiidalab/utils.py
- aiidalab/widgets.py
- requirements.txt
First revision to better follow the model-view model where the representation and underlying data are properly separated. Furthermore, this revision ensures that all git-specific functions are restricted to the app class. I hope I didn't miss anything.
> Refactor class structure to follow model-view and isolate git-related functions

- Pipfile
- aiidalab/__init__.py
- requirements.txt
- setup.json
> Prepare release 20.07.0b2

- aiidalab/app.py
This is not 100% debugged yet, but I'm creating this draft PR in case you want to do some testing.
> Revise installation release line specification

- aiidalab/app.py
> Use polling-based fallback observer if inotify watch limit is reached.

- aiidalab/app.py
With respect to the app's dependencies specification.
> Detect whether an app's environment is out-dated.

- aiidalab/app.py
- aiidalab/app_manager.py
- aiidalab/appstore.py
To reduce the size of the app module.
> Move AppManagerWidget class into app_manager module.

- .github/workflows/ci.yml
- aiidalab/app.py
- tests/test_app.py
This change set revises how the app installation, update determination, and app update flow is implemented and thus fixes issues #86 and #87. The change set also includes corresponding integration tests of these flows in various scenarios.
> Revise installation and update implementation

- Pipfile
- requirements.txt
This PR fixes pytests by adding `pytest_tornasync` as a dev dependency.
> Fix pytests

- Pipfile
- requirements.txt
> Move OPTIMADE client to the production environment

- docs/.gitignore
- docs/source/app_development/create.rst
- docs/source/app_development/example_qebands.rst
- docs/source/app_development/first_app.rst
- docs/source/app_development/index.rst
- docs/source/app_development/publish.rst
Closes #154.
Extends upon the current documentation on "How to develop an AiiDAlab app".
> Docs: How to develop an app

- docs/source/development/index.rst
And some basic summary of how those components interrelate.
> Add instructions for the development of aiidalab/-home.

- setup.cfg
> Remove pip from the dependency list

- aiidalab/utils.py
The previous configuration was broken such that requests would be cached
forever.
> Fix the caching of requests.

- aiidalab/app.py
- Move `is_installed` method from _AiidaLabApp to AiidaLabApp.
- Add logo attribute to _AiidaLabApp and AiidaLabApp.
> Changes to _AiidaLabApp and AiidaLabApp classes:

- docs/source/usage/index.rst
fixes https://github.com/aiidalab/aiidalab/issues/151
> docs: mention quantum mobile

- aiidalab/app.py
Fixes a regression that was introduced with that commit that broke the
installation of the correct version of an app from a git repository.
> Partially revert bb7ee4b26691ec6791b9370eb667b51c1bdecc4e.

- aiidalab/utils.py
> Respect global constraints file when installing app dependencies.

- aiidalab/app.py
- aiidalab/environment.py
- aiidalab/fetch.py
- aiidalab/metadata.py
- aiidalab/utils.py
- setup.cfg
Besides `fetch.py` I started working on `app.py` but quickly realized it will be more work than I had time for now so I only did the most obvious stuff for now. This allowed me to delete some skipped errors in setup.cfg.
> Add typing to fetch.py, more types in app.py

- .github/workflows/ci.yml
same as https://github.com/aiidalab/aiidalab-widgets-base/pull/569
> CI: Add Codecov token

- aiidalab/__main__.py
- aiidalab/app.py
- aiidalab/environment.py
- tests/conftest.py
- tests/static/app_with_setupcfg/setup.cfg
- tests/test_cli.py
- tests/test_conftest.py
- tests/test_install.py
Added a couple of simple CLI tests for the `aiidalab install` command + some supporting infrastructure and small fixes.
More installation tests are coming in a separate PR to keep the changes small.
> Add `aiidalab install` test

- .pre-commit-config.yaml
- aiidalab/app.py
- aiidalab/utils.py
- setup.cfg
> Add more types to aiidalab.app

- .pre-commit-config.yaml
- aiidalab/__main__.py
- aiidalab/app.py
- aiidalab/utils.py
- tests/static/app_registry.yaml
- tests/static/app_with_setupcfg/setup.cfg
- tests/test_appdataclass.py
Fixes https://github.com/aiidalab/aiidalab/issues/442. Fixes https://github.com/aiidalab/aiidalab/issues/326
Stacked on top of #447
> Skip invalid python requirements

- .gitignore
> Adding venv to .gitignore file
